version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: oidc_user
      POSTGRES_PASSWORD: oidc_pass
      POSTGRES_DB: oidc_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oidc_user -d oidc_service"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
